# Façade unique (bonus TP3) : Traefik (fourni par k3s) route par préfixe de chemin.
# Équivaut au gateway Traefik du docker-compose du TP.
# Exposé sur http://localhost:8081 (mapping k3d "8081:80@loadbalancer").
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tickrush
  namespace: tickrush
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 8080
          - path: /reservations
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 8080
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 3000
