apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: tickrush
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: tickrush/notification-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SMTP_HOST          # DNS de Service k8s de MailDev
              value: maildev
            - name: SMTP_PORT
              value: "1025"
            - name: MAIL_FROM
              value: noreply@tickrush.local
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "96Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
