apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tickrush

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - init-job.yaml

configMapGenerator:
  - name: kafka-topic-init
    files:
      - create-topics.sh

generatorOptions:
  disableNameSuffixHash: true
